server:
  port: 8080
  context-path: /jindu-manage
  session:
    timeout: 3600

spring:
  datasource:
    url: jdbc:mysql://172.17.21.59:3306/jindu
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      min-idle: 2
      max-idle: 10
      max-active: 20
      max-wait: 200
      test-on-borrow: true
  session:
      store-type: none
#      store-type: redis
  aop:
    auto: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages/
  redis:
       host: 172.17.21.59
       password: 123456
#    cluster:
#       nodes:
#              - 172.17.21.59:7003
#              - 172.17.21.59:7004
#              - 172.17.21.59:7005
#              - 172.17.21.63:7009
#              - 172.17.21.63:7011
#              - 172.17.21.63:7010

  data:
    mongodb:
        host: 172.17.21.59
        port: 27017
        dbname: jindu
        database: jindu
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB


#是否启动quartz任务扫描器
quartz:
  scan: false
mybatis:
  mapper-locations: classpath:sql/mapper/*.xml
  config-location: classpath:config/mybatis-config.xml
  type-aliases-package: com.ucsmy.jindu.manage.manage.entity

